#!/usr/bin/env python
import urllib2
import urllib
import argparse
import sys

def main(argv):
	#Arguments definition
	parser = argparse.ArgumentParser(description="Sends a pushover notification for an Icinga Alert")
	parser.add_argument('-t', '--token', help="Application token", default=None, required=True)
	parser.add_argument('-k', '--key', help="User/Group key", default=None, required=True)
	parser.add_argument('-H', '--host', help="Host name", default=None, required=True)
	parser.add_argument('-n', '--ntype', help="Notification type", default=None, required=True)
	parser.add_argument('-s', '--state', help="Host/Service state", default=None, required=True)
	parser.add_argument('message', help="Message content", default=None)
	parser.add_argument('-p', '--priority', help="Sets priority: -2=lowest, -1=low, 0=normal(default), 1=high, 2=emergency", type=int, default=0)
	args = parser.parse_args()
	
	#Building the request
	url = 'https://api.pushover.net/1/messages.json'
	parameters = {
		'token': args.token,
		'user': args.key,
		'message': args.message,
		'title': 'Icinga Alert on host ' + args.host + ' - ' + args.ntype,
		'priority': args.priority
    }

	#Sending the request
	data = urllib.urlencode(parameters)
	request = urllib2.Request(url, data)
	urllib2.urlopen(request)

if __name__=='__main__':
	main(sys.argv)